/**
 * WeatherGPT CAP v1.2 (Common Alerting Protocol) Service
 *
 * Generates OASIS/ITU-T X.1303 compliant CAP v1.2 alert messages in both
 * XML and JSON format. Compatible with India's NDMA SACHET platform and
 * WMO WIS 2.0 alert dissemination framework.
 *
 * Reference: http://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html
 */

// ─── CAP Constants ───────────────────────────────────────────────────────────

const CAP_XMLNS = 'urn:oasis:names:tc:emergency:cap:1.2'
const CAP_SENDER = 'weather-gpt@imd.gov.in'
const CAP_SENDER_NAME = 'WeatherGPT — India Meteorological Department'

const SEVERITY_MAP = {
  extreme:  'Extreme',
  severe:   'Severe',
  moderate: 'Moderate',
  minor:    'Minor',
  unknown:  'Unknown'
}

const URGENCY_MAP = {
  immediate: 'Immediate',
  expected:  'Expected',
  future:    'Future',
  past:      'Past',
  unknown:   'Unknown'
}

const CERTAINTY_MAP = {
  observed:  'Observed',
  likely:    'Likely',
  possible:  'Possible',
  unlikely:  'Unlikely',
  unknown:   'Unknown'
}

const CATEGORY_MAP = {
  weather:   'Met',
  flood:     'Met',
  cyclone:   'Met',
  tsunami:   'Geo',
  earthquake: 'Geo',
  fire:      'Fire',
  health:    'Health',
  security:  'Security',
  default:   'Met'
}

// ─── XML Escaping ────────────────────────────────────────────────────────────

function escapeXml(str) {
  if (!str) return ''
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

// ─── CAP XML Generator ──────────────────────────────────────────────────────

/**
 * Generate a CAP v1.2 compliant XML document from an internal alert object.
 *
 * @param {Object} alert - Internal alert object with fields:
 *   - _id: MongoDB ObjectId
 *   - type: 'weather' | 'flood' | 'cyclone' etc.
 *   - severity: 'extreme' | 'severe' | 'moderate' | 'minor'
 *   - title / headline: Alert headline
 *   - description: Alert body text
 *   - instruction: Recommended actions
 *   - areas: Array of { name, coordinates: { lat, lng } }
 *   - startTime / onset: Alert start
 *   - endTime / expires: Alert expiry
 *   - source: Originating authority
 *   - createdAt: Creation timestamp
 * @returns {string} CAP v1.2 XML string
 */
function generateCapXml(alert) {
  if (!alert) throw new Error('Alert object is required')

  const id = alert._id?.toString() || `WGPT-${Date.now()}`
  const sent = formatCapDate(alert.createdAt || new Date())
  const status = 'Actual'
  const msgType = 'Alert'
  const scope = 'Public'
  const source = escapeXml(alert.source || CAP_SENDER_NAME)

  // Info block
  const category = CATEGORY_MAP[alert.type?.toLowerCase()] || CATEGORY_MAP.default
  const event = escapeXml(alert.title || alert.headline || 'Weather Alert')
  const urgency = mapUrgency(alert)
  const severity = SEVERITY_MAP[alert.severity?.toLowerCase()] || 'Unknown'
  const certainty = mapCertainty(alert)
  const headline = escapeXml(alert.title || alert.headline || '')
  const description = escapeXml(alert.description || '')
  const instruction = escapeXml(alert.instruction || alert.actions?.join('. ') || 'Follow local authority instructions.')
  const onset = formatCapDate(alert.startTime || alert.onset || alert.createdAt || new Date())
  const expires = formatCapDate(alert.endTime || alert.expires || new Date(Date.now() + 24 * 60 * 60 * 1000))
  const senderName = escapeXml(alert.source || CAP_SENDER_NAME)

  // Area blocks
  const areas = (alert.areas || []).map(area => {
    const areaDesc = escapeXml(area.name || area.district || 'Affected Area')
    const lat = area.coordinates?.lat || area.lat
    const lng = area.coordinates?.lng || area.coordinates?.lon || area.lng || area.lon
    let areaXml = `        <area>\n          <areaDesc>${areaDesc}</areaDesc>\n`
    if (lat && lng) {
      // CAP circle: point + radius (0 = point, default 50km radius)
      areaXml += `          <circle>${lat},${lng} 50</circle>\n`
    }
    areaXml += `        </area>`
    return areaXml
  })

  // If no areas, add a default
  if (areas.length === 0) {
    areas.push('        <area>\n          <areaDesc>India — Affected Region</areaDesc>\n        </area>')
  }

  // Language
  const lang = alert.language || 'en-IN'

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<alert xmlns="${CAP_XMLNS}">
  <identifier>${escapeXml(id)}</identifier>
  <sender>${escapeXml(CAP_SENDER)}</sender>
  <sent>${sent}</sent>
  <status>${status}</status>
  <msgType>${msgType}</msgType>
  <scope>${scope}</scope>
  <code>IPAWSv1.0</code>
  <note>Generated by WeatherGPT — SIH 2026 (V-max Hackers)</note>
  <info>
    <language>${lang}</language>
    <category>${category}</category>
    <event>${event}</event>
    <urgency>${urgency}</urgency>
    <severity>${severity}</severity>
    <certainty>${certainty}</certainty>
    <onset>${onset}</onset>
    <expires>${expires}</expires>
    <senderName>${senderName}</senderName>
    <headline>${headline}</headline>
    <description>${description}</description>
    <instruction>${instruction}</instruction>
${areas.join('\n')}
  </info>
</alert>`

  return xml
}

// ─── CAP JSON Generator ─────────────────────────────────────────────────────

/**
 * Generate a CAP v1.2 compliant JSON representation.
 */
function generateCapJson(alert) {
  if (!alert) throw new Error('Alert object is required')

  const id = alert._id?.toString() || `WGPT-${Date.now()}`

  return {
    identifier: id,
    sender: CAP_SENDER,
    sent: formatCapDate(alert.createdAt || new Date()),
    status: 'Actual',
    msgType: 'Alert',
    scope: 'Public',
    code: ['IPAWSv1.0'],
    note: 'Generated by WeatherGPT — SIH 2026 (V-max Hackers)',
    info: [{
      language: alert.language || 'en-IN',
      category: [CATEGORY_MAP[alert.type?.toLowerCase()] || CATEGORY_MAP.default],
      event: alert.title || alert.headline || 'Weather Alert',
      urgency: mapUrgency(alert),
      severity: SEVERITY_MAP[alert.severity?.toLowerCase()] || 'Unknown',
      certainty: mapCertainty(alert),
      onset: formatCapDate(alert.startTime || alert.onset || alert.createdAt || new Date()),
      expires: formatCapDate(alert.endTime || alert.expires || new Date(Date.now() + 24 * 60 * 60 * 1000)),
      senderName: alert.source || CAP_SENDER_NAME,
      headline: alert.title || alert.headline || '',
      description: alert.description || '',
      instruction: alert.instruction || alert.actions?.join('. ') || 'Follow local authority instructions.',
      area: (alert.areas || []).map(area => ({
        areaDesc: area.name || area.district || 'Affected Area',
        circle: area.coordinates
          ? `${area.coordinates.lat},${area.coordinates.lng || area.coordinates.lon} 50`
          : undefined
      }))
    }]
  }
}

// ─── Helper Utilities ────────────────────────────────────────────────────────

/**
 * Format a date to CAP-compliant ISO 8601 with timezone offset.
 */
function formatCapDate(date) {
  const d = new Date(date)
  if (isNaN(d.getTime())) return new Date().toISOString()
  return d.toISOString().replace('Z', '+05:30') // IST offset for India
}

/**
 * Map alert urgency from internal data.
 */
function mapUrgency(alert) {
  if (alert.urgency) return URGENCY_MAP[alert.urgency.toLowerCase()] || 'Unknown'
  // Infer from severity
  const sev = (alert.severity || '').toLowerCase()
  if (sev === 'extreme') return 'Immediate'
  if (sev === 'severe') return 'Expected'
  if (sev === 'moderate') return 'Expected'
  return 'Future'
}

/**
 * Map alert certainty from internal data.
 */
function mapCertainty(alert) {
  if (alert.certainty) return CERTAINTY_MAP[alert.certainty.toLowerCase()] || 'Unknown'
  // Infer from severity
  const sev = (alert.severity || '').toLowerCase()
  if (sev === 'extreme' || sev === 'severe') return 'Likely'
  return 'Possible'
}

export {
  generateCapXml,
  generateCapJson,
  formatCapDate,
  CAP_XMLNS,
  CAP_SENDER,
  CAP_SENDER_NAME
}

export default {
  generateCapXml,
  generateCapJson,
  formatCapDate,
  CAP_XMLNS,
  CAP_SENDER,
  CAP_SENDER_NAME
}
